### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by BryanHunt** [BryanHunt/ember-split-view#36]
The split-view component test fails at:
```javascript
_setStyle: function() {
  var style = this.get('element').style;
```
`this.get('element')` is returning null.  This comes from:
```javascript
Ember.run.next(this, function() {
  this._setStyle();
});
```

I don't understand yet why the element is null.  `_setStyle()` is called prior to this and the element is not null.  I see the same call stacks in the dummy app, but element is never null.

**Comment by BryanHunt** [comment]
@BryanCrotaz do you have time to have a look at this?

**Comment by zfoster** [comment]
Any updates on this branch? I might be able to pull down and take a look, making sure there's nothing in progress. my app is failing tests after upgrading to ember 2.0, so to finish the upgrade i need to get this test passing

**Comment by BryanHunt** [comment]
I've looked at it a bit and don't understand why the first call to Ember.run works and the second fails.  This is currently beyond my understanding of Ember.

**Comment by zfoster** [comment]
I did some digging. I don't know the best way to fix this, but I can share my findings.

This assertion: 
```assert.equal(component._state, 'inDOM');``` 
is actually passing. The test is failing globally when qunit is trying to teardown the component. ```willDestroyElement``` is being called before this:
```
Ember.run.next(this, function() {
  this._setStyle();
});
```
so in ```_setStyle()```, ```this._state``` will return ```'destroying'```. The element is null because (I assume) qunit tore it down, so I think the solution is to make sure this block:
```
Ember.run.next(this, function() {
  this._setStyle();
});
```
isn't called after ```willDestroyElement```.

If you have advice on how to proceed, let me know. I can submit a PR with little guidance or time.

**Comment by BryanHunt** [comment]
Fixed

**Comment by zfoster** [comment]
I don't think that is a fix - anyone with a component test that renders this component will fail if they don't include this wait at the end, with the same error

**Comment by BryanHunt** [comment]
<img width="1160" alt="slack" src="https://cloud.githubusercontent.com/assets/504299/13551216/ec9e3398-e2f7-11e5-93a8-da694750d648.png">

**Comment by zfoster** [comment]
sounds good. I think if anybody has a component test that wraps this component it will still fail, however. Mine are still failing with a wait() added, but they pass with a small patch to ensure _setStyle doesn't get called when the component is destroying. Thanks!

**Comment by BryanHunt** [comment]
I would bring this up on Slack #test to see if anyone has a suggestion.
